#!/bin/sh

set -e
set -u

if [ ! -d ./dst ]; then
    mkdir ./dst
fi

cat \
    src/css/sanitize.css \
    src/css/typography.css \
    src/css/site.css \
    > src/css/all.css

./ssg6 ./src ./dst fsx https://fsx.github.io
